apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-deployment
  labels:
    app: sports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sports
  template:
    metadata:
      labels:
        app: sports
    spec:
      containers:
      - name: sports
        image: 239378270109.dkr.ecr.us-east-1.amazonaws.com/shopping-site-sports:def0e06fafdede313be736c6e128f6b747e6e3db
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sports-service
  labels:
    app: sports
spec:
  type: ClusterIP
  selector:
    app: sports
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
