apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-wheelers-deployment
  labels:
    app: two-wheelers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-wheelers
  template:
    metadata:
      labels:
        app: two-wheelers
    spec:
      containers:
      - name: two-wheelers
        image: 239378270109.dkr.ecr.us-east-1.amazonaws.com/shopping-site-toys:def0e06fafdede313be736c6e128f6b747e6e3db
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: two-wheelers-service
  labels:
    app: two-wheelers
spec:
  type: ClusterIP
  selector:
    app: two-wheelers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
